// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Web.Fiap.Carbono.Data.Contexts;

#nullable disable

namespace Web.Fiap.Carbono.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260615222828_CreateCarbonEmissionSchema")]
    partial class CreateCarbonEmissionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmissaoCarbonoModel", b =>
                {
                    b.Property<int>("IdEmissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_emissao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmissao"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_data_registro");

                    b.Property<string>("FonteEmissao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ds_fonte_emissao");

                    b.Property<int>("IdEtapa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_etapa");

                    b.Property<int>("IdFator")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_fator");

                    b.Property<string>("MetodoCalculo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ds_metodo_calculo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_observacao");

                    b.Property<decimal>("QuantidadeAtividade")
                        .HasColumnType("NUMBER(12,3)")
                        .HasColumnName("qt_atividade");

                    b.Property<decimal>("QuantidadeEmitida")
                        .HasColumnType("NUMBER(12,3)")
                        .HasColumnName("qtd_emitida");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("tp_unidade");

                    b.HasKey("IdEmissao")
                        .HasName("EC_EMISSOES_CARBONO_PK");

                    b.HasIndex("IdEtapa");

                    b.HasIndex("IdFator");

                    b.ToTable("EC_EMISSOES_CARBONO", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_EMISSOES_QTD_EMITIDA", "\"qtd_emitida\" >= 0");

                            t.HasCheckConstraint("CK_EC_EMISSOES_QT_ATIVIDADE", "\"qt_atividade\" > 0");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmpresaModel", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_empresa");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("ds_cnpj");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("nm_estado");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("nm_empresa");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("nm_pais");

                    b.Property<string>("SetorAtuacao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ds_setor_atuacao");

                    b.HasKey("IdEmpresa")
                        .HasName("EC_EMPRESAS_PK");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UK_EC_EMPRESAS_CNPJ");

                    b.ToTable("EC_EMPRESAS", (string)null);
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EtapaCadeiaModel", b =>
                {
                    b.Property<int>("IdEtapa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_etapa");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtapa"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_data_inicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_descricao");

                    b.Property<string>("Destino")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("ds_destino");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_fornecedor");

                    b.Property<int>("IdLote")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_lote");

                    b.Property<string>("OrdemEtapa")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ds_ordem_etapa");

                    b.Property<string>("Origem")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("ds_origem");

                    b.Property<string>("TipoEtapa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("tp_tipo_etapa");

                    b.HasKey("IdEtapa")
                        .HasName("EC_ETAPAS_CADEIA_PK");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdLote");

                    b.ToTable("EC_ETAPAS_CADEIA", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_ETAPAS_DATAS", "\"dt_data_fim\" IS NULL OR \"dt_data_fim\" >= \"dt_data_inicio\"");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FatorEmissaoModel", b =>
                {
                    b.Property<int>("IdFator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_fator");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFator"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("st_ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("tp_escopo");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("NVARCHAR2(155)")
                        .HasColumnName("ds_fonte");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ds_referencia");

                    b.Property<string>("UnidadeBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ds_unidade_base");

                    b.Property<decimal>("ValorFatorCo2e")
                        .HasColumnType("NUMBER(12,6)")
                        .HasColumnName("vl_fator_co2e");

                    b.HasKey("IdFator")
                        .HasName("EC_FATORES_EMISSAO_PK");

                    b.ToTable("EC_FATORES_EMISSAO", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_FATORES_ATIVO", "\"st_ativo\" IN (''S'', ''N'')");

                            t.HasCheckConstraint("CK_EC_FATORES_ESCOPO", "\"tp_escopo\" IN (''ESCOPO_1'', ''ESCOPO_2'', ''ESCOPO_3'')");

                            t.HasCheckConstraint("CK_EC_FATORES_VALOR", "\"vl_fator_co2e\" > 0");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FornecedorModel", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_fornecedor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFornecedor"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("st_ativo");

                    b.Property<string>("CertificacaoEsg")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ds_certificacao_esg");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("ds_cnpj");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("nm_estado");

                    b.Property<string>("NomeFornecedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("nm_fornecedor");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("nm_pais");

                    b.Property<string>("TipoFornecedor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("tp_fornecedor");

                    b.HasKey("IdFornecedor")
                        .HasName("EC_FORNECEDORES_PK");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UK_EC_FORNECEDORES_CNPJ");

                    b.ToTable("EC_FORNECEDORES", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_FORNECEDORES_ATIVO", "\"st_ativo\" IN (''S'', ''N'')");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.LoteProducaoModel", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_lote");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("cd_codigo_lote");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_data_producao");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_data_validade");

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_produto");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("qt_quantidade");

                    b.Property<string>("StatusLote")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("st_status_lote");

                    b.HasKey("IdLote")
                        .HasName("EC_LOTES_PRODUCAO_PK");

                    b.HasIndex("IdProduto");

                    b.ToTable("EC_LOTES_PRODUCAO", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_LOTES_DATAS", "\"dt_data_validade\" >= \"dt_data_producao\"");

                            t.HasCheckConstraint("CK_EC_LOTES_QTDE", "\"qt_quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.ProdutoModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_produto");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("st_ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_descricao");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("nm_produto");

                    b.Property<string>("TipoCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("tp_categoria");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ds_unidade_medida");

                    b.HasKey("IdProduto")
                        .HasName("EC_PRODUTOS_PK");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("EC_PRODUTOS", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_PRODUTOS_ATIVO", "\"st_ativo\" IN (''S'', ''N'')");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmissaoCarbonoModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.EtapaCadeiaModel", "EtapaCadeia")
                        .WithMany("EmissoesCarbono")
                        .HasForeignKey("IdEtapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_EMISSOES_ETAPAS");

                    b.HasOne("Web.Fiap.Carbono.Models.FatorEmissaoModel", "FatorEmissao")
                        .WithMany("EmissoesCarbono")
                        .HasForeignKey("IdFator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_EMISSOES_FATORES");

                    b.Navigation("EtapaCadeia");

                    b.Navigation("FatorEmissao");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EtapaCadeiaModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.FornecedorModel", "Fornecedor")
                        .WithMany("EtapasCadeia")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_ETAPAS_FORNECEDORES");

                    b.HasOne("Web.Fiap.Carbono.Models.LoteProducaoModel", "LoteProducao")
                        .WithMany("EtapasCadeia")
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_ETAPAS_LOTES");

                    b.Navigation("Fornecedor");

                    b.Navigation("LoteProducao");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.LoteProducaoModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.ProdutoModel", "Produto")
                        .WithMany("LotesProducao")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_LOTES_PRODUTOS");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.ProdutoModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.EmpresaModel", "Empresa")
                        .WithMany("Produtos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_PRODUTOS_EMPRESAS");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmpresaModel", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EtapaCadeiaModel", b =>
                {
                    b.Navigation("EmissoesCarbono");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FatorEmissaoModel", b =>
                {
                    b.Navigation("EmissoesCarbono");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FornecedorModel", b =>
                {
                    b.Navigation("EtapasCadeia");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.LoteProducaoModel", b =>
                {
                    b.Navigation("EtapasCadeia");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.ProdutoModel", b =>
                {
                    b.Navigation("LotesProducao");
                });
#pragma warning restore 612, 618
        }
    }
}
