// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Web.Fiap.Carbono.Data.Contexts;

#nullable disable

namespace Web.Fiap.Carbono.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260615225615_CreateCarbonEmissionSchema")]
    partial class CreateCarbonEmissionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmissaoCarbonoModel", b =>
                {
                    b.Property<int>("IdEmissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMISSAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmissao"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DATA_REGISTRO");

                    b.Property<string>("FonteEmissao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_FONTE_EMISSAO");

                    b.Property<int>("IdEtapa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ETAPA");

                    b.Property<int>("IdFator")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FATOR");

                    b.Property<string>("MetodoCalculo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_METODO_CALCULO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<decimal>("QuantidadeAtividade")
                        .HasColumnType("NUMBER(12,3)")
                        .HasColumnName("QT_ATIVIDADE");

                    b.Property<decimal>("QuantidadeEmitida")
                        .HasColumnType("NUMBER(12,3)")
                        .HasColumnName("QTD_EMITIDA");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_UNIDADE");

                    b.HasKey("IdEmissao")
                        .HasName("EC_EMISSOES_CARBONO_PK");

                    b.HasIndex("IdEtapa");

                    b.HasIndex("IdFator");

                    b.ToTable("EC_EMISSOES_CARBONO", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_EMISSOES_QTD_EMITIDA", "\"QTD_EMITIDA\" >= 0");

                            t.HasCheckConstraint("CK_EC_EMISSOES_QT_ATIVIDADE", "\"QT_ATIVIDADE\" > 0");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmpresaModel", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("DS_CNPJ");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("NM_ESTADO");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_EMPRESA");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_PAIS");

                    b.Property<string>("SetorAtuacao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_SETOR_ATUACAO");

                    b.HasKey("IdEmpresa")
                        .HasName("EC_EMPRESAS_PK");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UK_EC_EMPRESAS_CNPJ");

                    b.ToTable("EC_EMPRESAS", (string)null);
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EtapaCadeiaModel", b =>
                {
                    b.Property<int>("IdEtapa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ETAPA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtapa"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DATA_INICIO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("Destino")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_DESTINO");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FORNECEDOR");

                    b.Property<int>("IdLote")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOTE");

                    b.Property<string>("OrdemEtapa")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("DS_ORDEM_ETAPA");

                    b.Property<string>("Origem")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_ORIGEM");

                    b.Property<string>("TipoEtapa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TP_TIPO_ETAPA");

                    b.HasKey("IdEtapa")
                        .HasName("EC_ETAPAS_CADEIA_PK");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdLote");

                    b.ToTable("EC_ETAPAS_CADEIA", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_ETAPAS_DATAS", "\"DT_DATA_FIM\" IS NULL OR \"DT_DATA_FIM\" >= \"DT_DATA_INICIO\"");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FatorEmissaoModel", b =>
                {
                    b.Property<int>("IdFator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FATOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFator"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_ESCOPO");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("NVARCHAR2(155)")
                        .HasColumnName("DS_FONTE");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_REFERENCIA");

                    b.Property<string>("UnidadeBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_UNIDADE_BASE");

                    b.Property<decimal>("ValorFatorCo2e")
                        .HasColumnType("NUMBER(12,6)")
                        .HasColumnName("VL_FATOR_CO2E");

                    b.HasKey("IdFator")
                        .HasName("EC_FATORES_EMISSAO_PK");

                    b.ToTable("EC_FATORES_EMISSAO", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_FATORES_ATIVO", "\"ST_ATIVO\" IN (''S'', ''N'')");

                            t.HasCheckConstraint("CK_EC_FATORES_ESCOPO", "\"TP_ESCOPO\" IN (''ESCOPO_1'', ''ESCOPO_2'', ''ESCOPO_3'')");

                            t.HasCheckConstraint("CK_EC_FATORES_VALOR", "\"VL_FATOR_CO2E\" > 0");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FornecedorModel", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FORNECEDOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFornecedor"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("CertificacaoEsg")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_CERTIFICACAO_ESG");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("DS_CNPJ");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("NM_ESTADO");

                    b.Property<string>("NomeFornecedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_FORNECEDOR");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_PAIS");

                    b.Property<string>("TipoFornecedor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TP_FORNECEDOR");

                    b.HasKey("IdFornecedor")
                        .HasName("EC_FORNECEDORES_PK");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UK_EC_FORNECEDORES_CNPJ");

                    b.ToTable("EC_FORNECEDORES", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_FORNECEDORES_ATIVO", "\"ST_ATIVO\" IN (''S'', ''N'')");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.LoteProducaoModel", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CD_CODIGO_LOTE");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DATA_PRODUCAO");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DATA_VALIDADE");

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("QT_QUANTIDADE");

                    b.Property<string>("StatusLote")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ST_STATUS_LOTE");

                    b.HasKey("IdLote")
                        .HasName("EC_LOTES_PRODUCAO_PK");

                    b.HasIndex("IdProduto");

                    b.ToTable("EC_LOTES_PRODUCAO", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_LOTES_DATAS", "\"DT_DATA_VALIDADE\" >= \"DT_DATA_PRODUCAO\"");

                            t.HasCheckConstraint("CK_EC_LOTES_QTDE", "\"QT_QUANTIDADE\" > 0");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.ProdutoModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_PRODUTO");

                    b.Property<string>("TipoCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TP_CATEGORIA");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_UNIDADE_MEDIDA");

                    b.HasKey("IdProduto")
                        .HasName("EC_PRODUTOS_PK");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("EC_PRODUTOS", null, t =>
                        {
                            t.HasCheckConstraint("CK_EC_PRODUTOS_ATIVO", "\"ST_ATIVO\" IN (''S'', ''N'')");
                        });
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmissaoCarbonoModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.EtapaCadeiaModel", "EtapaCadeia")
                        .WithMany("EmissoesCarbono")
                        .HasForeignKey("IdEtapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_EMISSOES_ETAPAS");

                    b.HasOne("Web.Fiap.Carbono.Models.FatorEmissaoModel", "FatorEmissao")
                        .WithMany("EmissoesCarbono")
                        .HasForeignKey("IdFator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_EMISSOES_FATORES");

                    b.Navigation("EtapaCadeia");

                    b.Navigation("FatorEmissao");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EtapaCadeiaModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.FornecedorModel", "Fornecedor")
                        .WithMany("EtapasCadeia")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_ETAPAS_FORNECEDORES");

                    b.HasOne("Web.Fiap.Carbono.Models.LoteProducaoModel", "LoteProducao")
                        .WithMany("EtapasCadeia")
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_ETAPAS_LOTES");

                    b.Navigation("Fornecedor");

                    b.Navigation("LoteProducao");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.LoteProducaoModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.ProdutoModel", "Produto")
                        .WithMany("LotesProducao")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_LOTES_PRODUTOS");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.ProdutoModel", b =>
                {
                    b.HasOne("Web.Fiap.Carbono.Models.EmpresaModel", "Empresa")
                        .WithMany("Produtos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EC_PRODUTOS_EMPRESAS");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EmpresaModel", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.EtapaCadeiaModel", b =>
                {
                    b.Navigation("EmissoesCarbono");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FatorEmissaoModel", b =>
                {
                    b.Navigation("EmissoesCarbono");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.FornecedorModel", b =>
                {
                    b.Navigation("EtapasCadeia");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.LoteProducaoModel", b =>
                {
                    b.Navigation("EtapasCadeia");
                });

            modelBuilder.Entity("Web.Fiap.Carbono.Models.ProdutoModel", b =>
                {
                    b.Navigation("LotesProducao");
                });
#pragma warning restore 612, 618
        }
    }
}
